spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: moongchi
    password: wkdbfa705
    url: jdbc:mysql://13.124.253.176:3333/66days?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true
